// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrr6675mTpf7e99EcdDCLu_RabKlRa08',
    appId: '1:101365714785:web:d683b5281161b06a733f20',
    messagingSenderId: '101365714785',
    projectId: 'skillsync-b212e',
    authDomain: 'skillsync-b212e.firebaseapp.com',
    storageBucket: 'skillsync-b212e.firebasestorage.app',
    measurementId: 'G-SRXQ0KSSKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWhoNg7S_tEOXFw-MB3GagBp6Xt23c44',
    appId: '1:101365714785:android:a0bb3c211f545dc5733f20',
    messagingSenderId: '101365714785',
    projectId: 'skillsync-b212e',
    storageBucket: 'skillsync-b212e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7PV4aABsCxfxqUqWA5LESFQugFnRUu3Y',
    appId: '1:101365714785:ios:140177e727b1368b733f20',
    messagingSenderId: '101365714785',
    projectId: 'skillsync-b212e',
    storageBucket: 'skillsync-b212e.firebasestorage.app',
    iosBundleId: 'com.example.counterSteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7PV4aABsCxfxqUqWA5LESFQugFnRUu3Y',
    appId: '1:101365714785:ios:140177e727b1368b733f20',
    messagingSenderId: '101365714785',
    projectId: 'skillsync-b212e',
    storageBucket: 'skillsync-b212e.firebasestorage.app',
    iosBundleId: 'com.example.counterSteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtrr6675mTpf7e99EcdDCLu_RabKlRa08',
    appId: '1:101365714785:web:dc8cd53acb69889b733f20',
    messagingSenderId: '101365714785',
    projectId: 'skillsync-b212e',
    authDomain: 'skillsync-b212e.firebaseapp.com',
    storageBucket: 'skillsync-b212e.firebasestorage.app',
    measurementId: 'G-7VB7QFVXH2',
  );
}
